### ISSUE TITLE
The generated conda package cannot run with glibc 2.12

### ISSUE THREAD

**Issue by chengdi123000** [Cantera/conda-recipes#10]
Recently I used miniconda3 to install cantera on a RHEL 6.7 HPC. It report error about the glibc version. The conda package is compiled using trusty ([travis-ci.org build env overview](https://docs.travis-ci.com/user/reference/overview/)), which uses glibc 2.19 according to the [package list of trusty][(https://packages.ubuntu.com/trusty/allpackages). However, RHEL/[CentOS 6](http://mirror.centos.org/centos/6/os/x86_64/Packages/) uses 2.12 and [CentOS 7](http://mirror.centos.org/centos/7/os/x86_64/Packages/) uses 2.17.

Considering the backward compatibility issue of cantera in many HPC platform (glibc itself is designed to be [backward compatible and portable](https://www.gnu.org/software/libc/)), I suggest to use docker function in travis-ci to run the build and test in CentOS 6. There is a sample code [here](https://github.com/opensciencegrid/htcondor-ce/blob/master/.travis.yml)

I also considerred use ubuntu 12.04 in travis-ci, how ever, it uses [glibc 2.15](http://old-releases.ubuntu.com/releases/precise/ubuntu-12.04.4-server-amd64.list) and I cannot find downgrade guide of glibc. 

Another idea I can imagine is to use static-linking (at least to all libraries pointed to `/lib` and `/lib64` ) to generate the `*.so` file in cantera package. It should works better than shared link with size inflation (considering the size of [glibc 2.12 rpm](https://rpmfind.net/linux/RPM/centos/6.9/x86_64/Packages/glibc-2.12-1.209.el6.x86_64.html) is about 13MB). Further, for exascale HPC application, static linking is necessary to accelerate loading of the program. And the RAM of modern HPC is horribly larger than cantera need.

**Comment by speth** [comment]
There is no expectation for these packages to work on operating systems that are past their end-of-life (even by Red Hat's very generous definition of life). You can always compile Cantera yourself to meet the specific needs of your system.

**Comment by chengdi123000** [comment]
It makes sense.
