### ISSUE TITLE
building for ARM architecture

### ISSUE THREAD

**Issue by rddaz2013** [Cantera/conda-recipes#17]
Has cantera ever been complied for ARM (raspberry3) ?

**Comment by speth** [comment]
I think you'd be better off asking this on the Users' Group.

**Comment by bryanwweber** [comment]
@rddaz2013 Since this was filed on `conda-recipes`, I can say that the conda recipe has not been built for ARM by any of the core developers. Maybe someone else has, hence, asking on the Users' Group.

**Comment by bryanwweber** [comment]
Packages for ARM are now available from the `conda-forge` channel: https://anaconda.org/conda-forge/cantera :tada:
