### ISSUE TITLE
Feature request: include C++ headers in conda

### ISSUE THREAD

**Issue by ischoegl** [Cantera/conda-recipes#18]
### Cantera version
2.4.0 installed via conda (e.g. anaconda3-5.2.0)

 * Expected Behavior: C++ header files should be distributed in the standard `include/cantera/...` folders
 * Actual Behavior: While a compilation from source does install header files, the conda installation does not.
 * Steps to reproduce: Install cantera using conda.

**Comment by bryanwweber** [comment]
Sorry, the branch is actually here: https://github.com/Cantera/conda-recipes/pull/13

**Comment by bryanwweber** [comment]
See #19

**Comment by bryanwweber** [comment]
@ischoegl Once the builds finish, you should be able to
```
conda install -c cantera/label/dev libcantera-devel
```
to install the headers and .so files. Please feel free to test and post any issues here 🎉

**Comment by ischoegl** [comment]
@bryanwweber ... just pulled it and it works beautifully ... thanks!

In case you're interested, I tested this for the example showing [how to compile new (or modified) code against stock cantera](https://github.com/ischoegl/ctapp) that I put together some time ago.

**Comment by bryanwweber** [comment]
I think this feature request is complete, as far as it goes. Let's leave #20 open to track fixing that issue.
