### ISSUE TITLE
Cantera conda package forces downgrade of recent numpy versions

### ISSUE THREAD

**Issue by daharn** [Cantera/conda-recipes#21]
### Cantera version
2.4.0
### Operating System
any
### Python version
3.7
### Behavior
Installing the latest stable version of Cantera using conda enforces `numpy` to be of version `1.15.*`, essentially leading to a forced downgrade if a more recent version is installed. Since the latest dev-version only specifies `numpy >=1.11.3 `, is this actually necessary?

I am asking because I experienced some problems with other packages when downgrading numpy (which also shouldn't happen, but that's a different story).

**Comment by bryanwweber** [comment]
I think I'll wait until packages for Python 3.8 are available from the official conda channels.

**Comment by daharn** [comment]
Just to confirm that this issue is still there and really messes up my anaconda environment. Current numpy version is now 1.18 and there seem to be a lot of dependencies being affected when forcing a downgrade through cantera.

**Comment by bryanwweber** [comment]
@daharn yes, this issue is resolved with the developer version. You can use

```
conda install -c Cantera/label/dev cantera
```


or create a new environment, which is really best practice anyways.

**Comment by daharn** [comment]
> @daharn yes, this issue is resolved with the developer version. You can use
> 
> ```
> conda install -c Cantera/label/dev cantera
> ```
> 
> or create a new environment, which is really best practice anyways.

Yes, using the developer version is my current workaround as well. However, I don't suppose it is the solution that most people would initially choose, so an updated stable build would still be desirable. 

Are you sure a new environment would equivalently solve this issue? My experience with environments is limited, but wouldn't the numpy version inside this environment be downgraded as well, hence causing the same problems?

**Comment by bryanwweber** [comment]
@daharn there would be an entirely new version of all the dependencies installed in a new environment, so there shouldn't be any conflicts. The only way you might end up with conflicts is if you need a specific version of another package that doesn't support the NumPy that Cantera does.

**Comment by bryanwweber** [comment]
This should now be resolved by v2.5.1!
