### ISSUE TITLE
License for code contained in this repo?

### ISSUE THREAD

**Issue by inducer** [Cantera/conda-recipes#23]
In https://github.com/conda-forge/staged-recipes/pull/13414, I have started putting together a conda-forge recipe for cantera, starting from the recipes in this repo. In [this comment](https://github.com/conda-forge/staged-recipes/pull/13414#issuecomment-741396982), @isuruf (rightfully) asks what license applies to this recipe. Could you provide answer, ideally by committing a license file to the repo? Thanks!

**Comment by bryanwweber** [comment]
Ah, great question. I think we'll apply the BSD 3-clause here, without the modifications used in the main Cantera repo, since this code was all developed more recently. Let me discuss with @speth though!

**Comment by speth** [comment]
Agreed, @bryanwweber. The standard BSD 3 clause, with the copyright assigned to "Cantera Developers" seems like a very reasonable choice. No need to overthink this.

**Comment by inducer** [comment]
Thanks!
