### ISSUE TITLE
Installing Matlab interface via conda fails if MATLAB folder is not in standard location

### ISSUE THREAD

**Issue by daharn** [Cantera/conda-recipes#28]
From the comments inside `post-link.sh` and `post-link.bat` I realize that their current working is already a compromise.

However, I wanted to point out that at least on Windows, it is currently impossible to install the `cantera-matlab` package when the folder %USERPROFILE%\Documents\MATLAB does not exist. I would say this can be quite common, because many people tend to separate their User folders from their system partition.  The only solution is to manually create the folder.

I haven't tested whether Linux is more forthcoming here.

In any case, I would suggest to update the script with a warning if the MATLAB folder could not be located, so the user than knows they have to provide the startup data manually.

**Comment by bryanwweber** [comment]
Awesome, thanks for the feedback! I'm not super familiar with Windows, so I want to ask, where does `%USERPROFILE%` point if not to the drive with the `Documents` folder? Does MATLAB's startup folder change if you put your user folder on a separate partition?

**Comment by daharn** [comment]
%USERPROFILE% will usually point to to "C:\Users\<username>" unless explicitly reset by the user (unlikely and not recommended). 

I have to say I can't remember whether Matlab put the folder into the moved location on its own or if I had to do it myself.

The answer to [this question](https://superuser.com/questions/1132288/windows-command-prompt-get-relocated-users-documents-folder) suggests to query the Windows registry, but I am not sure if this is a more robust solution than just inviting the user to do it themselves.

**Comment by daharn** [comment]
> Thanks! Is there another environment variable that points to `Documents`, wherever that happens to be located?

According to the SuperUser question linked above, using the registry entry seems to be the only way.

**Comment by speth** [comment]
This is pretty difficult for any of us to test. @daharn, can you confirm if the following command (mostly from the Superuser post you linked to) outputs the path you expect?
```bat
powershell -ExecutionPolicy Bypass -Command "[Environment]::GetFolderPath('MyDocuments') | Out-File 'docspath.tmp'"
type docspath.tmp
```

**Comment by daharn** [comment]
Yes, this produces the correct path. Alternatively, to avoid the creation of a temporary file, the "correct" approach seems to be 

```batchfile
FOR /F %%G IN ('powershell -ExecutionPolicy Bypass -Command "[Environment]::GetFolderPath('MyDocuments')"') DO SET MATLAB_STARTUP=%%G\MATLAB\startup.m
```

**Comment by bryanwweber** [comment]
The commit comment got over-eager, I'm reopening this until we can check with actual packages that they do the right thing.

**Comment by speth** [comment]
> ```batchfile
> FOR /F %%G IN ('powershell -ExecutionPolicy Bypass -Command "[Environment]::GetFolderPath('MyDocuments')"') DO SET MATLAB_STARTUP=%%G\MATLAB\startup.m
> ```

Unfortunately, this version just gives me the error message:
```
%%G was unexpected at this time.
```

**Comment by speth** [comment]
OK, I managed to get the `FOR`-based solution to work after all ([f54e465](https://github.com/Cantera/conda-recipes/commit/f54e465aea54b01f13dcd8c8b0d2678c24bc1d7c)), thanks to one of the answers in [this SO post](https://stackoverflow.com/questions/6359820/how-to-set-commands-output-as-a-variable-in-a-batch-file). I've tested this and confirmed that it works as expected, even if the path to the "Documents" folder contains spaces.
