### ISSUE TITLE
`Conda Install` Development Cantera Version 3.0.0a2

### ISSUE THREAD

**Issue by dylanrubini** [Cantera/conda-recipes#31]
**Problem description**

**Steps to reproduce**

I'm trying to install the Cantera development version 3.0.0a2 using `conda`. This is because I want to test the preconditioner functionality 

I use the following command to create a new `conda` environment and install the latest dev Cantera version (note that I locally removed the stable Cantera version from my machine) :

``` shell
conda create --name ct-dev --channel cantera/label/dev cantera ipython matplotlib jupyter
```
Using `ipython` I check the version of Cantera installed

```python
import cantera as ct
print(ct.__version__)
# 2.6.0
```
But version 2.6.0 gets printed

Using `conda list` command I can see that version 3.0.0a2 is installed. But, doing `pip list` shows that there is also the 2.6.0 version installed even though I never installed it. It seems to get installed automatically when I install the dev version 3.0.0a2 using `conda`

Is there any way to fix this? Am I doing something wrong?

Thank you in advance for the help!

**Behavior**

**System information**

- Cantera version: 3.0.0a2
- OS: Centos7 Linux
-  Architecture: x86
- Python Version: 3.9.12
- Python/MATLAB/other software versions: Python

**Attachments**

**Additional context**

**Comment by ischoegl** [comment]
I just built the `conda` package locally (while trying to figure out how those work - see #32), and ended up with the same issue. Watching the build, I *saw* that `conda` checked out the correct version from `main` initially (per `meta.yaml`). Alas, the installed version is `2.6.0`.

Fwiw, here's the output I get  when installing:
```
(ct-test) [ischoegl@xps13 conda-recipes]$ conda install -c file:///opt/conda/envs/conda-bld/conda-bld/ cantera
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/ct-test

  added / updated specs:
    - cantera


The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  cantera            conda-bld/linux-64::cantera-3.0.0a2-py39h6cd0baa_0
  h5py               pkgs/main/linux-64::h5py-3.7.0-py39h737f45e_0
  hdf5               pkgs/main/linux-64::hdf5-1.10.6-h3ffc7dd_1
  intel-openmp       pkgs/main/linux-64::intel-openmp-2021.4.0-h06a4308_3561
  libcantera         conda-bld/linux-64::libcantera-3.0.0a2-h3fd9d12_0
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-11.2.0-h00389a5_1
  libgfortran5       pkgs/main/linux-64::libgfortran5-11.2.0-h1234567_1
  mkl                pkgs/main/linux-64::mkl-2021.4.0-h06a4308_640
  mkl-service        pkgs/main/linux-64::mkl-service-2.4.0-py39h7f8727e_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.1-py39hd3c417c_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.2-py39h51133e4_0
  numpy              pkgs/main/linux-64::numpy-1.23.1-py39h6c91a56_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.23.1-py39ha15fc14_0
  ruamel.yaml        pkgs/main/linux-64::ruamel.yaml-0.16.12-py39h27cfd23_1
  ruamel.yaml.clib   pkgs/main/linux-64::ruamel.yaml.clib-0.2.6-py39h7f8727e_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
```
Here, `conda-bld` refers to my local "channel".

**Comment by bryanwweber** [comment]
@ischoegl can you add the `nomkl` package? `conda install -c file:///opt/conda/envs/conda-bld/conda-bld/ nomkl cantera`

**Comment by ischoegl** [comment]
No difference.

**Comment by bryanwweber** [comment]
Dang, that should at least error out if there's a hard dependency on `mkl`.

**Comment by ischoegl** [comment]
> Dang, that should at least error out if there's a hard dependency on `mkl`.

```
[...]

The following packages will be REMOVED:

  mkl_fft-1.3.1-py39hd3c417c_0
  mkl_random-1.2.2-py39h51133e4_0

The following packages will be UPDATED:

  blas                                              1.0-mkl --> 1.0-openblas

The following packages will be DOWNGRADED:

  numpy                               1.21.5-py39h6c91a56_3 --> 1.21.5-py39hf838250_3
  numpy-base                          1.21.5-py39ha15fc14_3 --> 1.21.5-py39h1e6e340_3

[...]
```

**Comment by bryanwweber** [comment]
Yeah, but I'm pretty sure that the Linux package links to MKL as the BLAS, via `blas_lapack_libs` SCons configuration.

**Comment by ischoegl** [comment]
Like @dylanrubini, I also get `Cantera 2.6` when I issue `pip list`. Could it be that things get crossed when installing the wheel?

**Comment by ischoegl** [comment]
Could it be that `--user` should be added to the other branches also?
https://github.com/Cantera/cantera/blob/ee1ad0b601ccd94dcc6b86749428a0c7db74bd23/interfaces/cython/SConscript#L128-L142
