### ISSUE TITLE
conda-forge update

### ISSUE THREAD

**Issue by ischoegl** [Cantera/conda-recipes#36]
At this point, build scripts have diverged from [conda-forge/cantera-feedstock](https://github.com/conda-forge/cantera-feedstock). Once all recipes are stable here, the ``conda-forge`` recipes need to be updated accordingly. 

I am posting here as I'm not sure who is following issues or bug report on ``conda-forge``.

**Comment by bryanwweber** [comment]
Me and @inducer are the maintainers of that recipe. I think it will be easier to update that recipe when we get ready to release 3.0, since pre-releases generally aren't done for conda-forge, IIRC.

**Comment by ischoegl** [comment]
I believe this is also done.
