### ISSUE TITLE
Broken packaging action for 3.1.0a2

### ISSUE THREAD

**Issue by ischoegl** [Cantera/conda-recipes#48]
It appears that the packaging job is currently broken. This became apparent when checking on a user question https://github.com/Cantera/cantera/pull/1682#issuecomment-2036626237. While packaging actions on Cantera/cantera triggered via `packaging.yml` appear to pass ([GH Action example](https://github.com/Cantera/cantera/actions/runs/8543559685)), the triggered action does not ([GH Action example](https://github.com/Cantera/conda-recipes/actions/runs/8543563144)).

It may be worth an enhancement request to look into passing back flags indicating success from triggered actions?

**Comment by bryanwweber** [comment]
> It may be worth an enhancement request to look into passing back flags indicating success from triggered actions?

When I implemented this, it wasn't possible to set the state of an existing job based on a job in an external repo, I'm not sure if that's changed. Essentially, the job in `Cantera/cantera` that triggers the workflow run here completes successfully so it gets a green check without waiting to see the state of the called workflow. However, the status on the main branch in `Cantera/cantera` does report the failure:

<img width="972" alt="image" src="https://github.com/Cantera/conda-recipes/assets/4396228/996c1b6b-7b22-4822-bb92-fc97f60558a2">

**Comment by ischoegl** [comment]
@bryanwweber ... thanks for the comment. I've never looked into triggering actions myself, so this chart may have misled me (note the last part: "send jobs status to Cantera/cantera"): 
<img width="1103" alt="image" src="https://github.com/Cantera/conda-recipes/assets/12603999/c70cf635-6e28-4a03-a8db-9241eda2f830">

**Comment by bryanwweber** [comment]
Right, that succeeded because the status was sent successfully back to `Cantera/cantera`. It's not representative of the overall state of the workflow, which shows as failed in the main Actions view. I think it's just a limitation of cross-repo workflows, unfortunately.

**Comment by bryanwweber** [comment]
I think this is resolved.
