### ISSUE TITLE
Add script to auto-generate build matrix

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/conda-recipes#9]
@speth Does the code here: https://github.com/Cantera/conda-recipes/commit/54581e53b94934953a429ca92aba854a4e0133ee make sense to include? The intended use is that a maintainer runs `generate-ci-builds.py` locally and commits the changes to `.travis.yml` and `appveyor.yml`. Ideally, only the build matrix will change after this first commit where things get a little bit reformatted. The only dependency is `ruamel.yaml>=0.15.0`, but it only has to be installed locally by a maintainer when they want to update things, users don't have to do anything.

My only concern is the reformatting of `.travis.yml` and `appveyor.yml`. That should only happen this one time though. Thoughts?

PS This isn't a PR because it generates a pretty large number of builds that I didn't want to kick off again :smile: Seems like the builds are working fine: https://travis-ci.org/Cantera/conda-recipes/builds/242566802 and https://ci.appveyor.com/project/Cantera/conda-recipes/build/1.0.57 I also have a similar changeset for the master branch that I didn't push yet because, again, a bunch of builds

**Comment by speth** [comment]
Conceptually, I think this makes sense.

The new script probably needs a bit of documentation describing this intended use, including the requirement for a bleeding-edge version of ruamel and where to get that (I guess you have to get this from conda-forge for the time being). The `matrix` sections of the YAML files should have a comment mentioning that they are autogenerated and should be updated by running this script.

I might suggest naming the script 'generate-build-matrix.py`.

I think you can reduce the amount of reformatting that is occurring if you set `yaml.indent` to 2, but I'm not really concerned about the reformatting in any case.

**Comment by bryanwweber** [comment]
OK I pushed 49e47346e9f47cb689682e47e99203db418fd6da and a8cd37739c838beebb9df0f1324b2c8ca67251ee to `2.3` and `master` (respectively).

Setting `yaml.indent=2` results in an invalid YAML file because you end up with, for example

```
matrix:
  include:
    - os: linux
    env: ...
```
where the `env` isn't indented enough. Anyways, since its just this once, I'm not worried about it. Thanks for taking a look!

**Comment by speth** [comment]
Huh, seems like that must be a bug in the YAML emitter, but certainly not worth fighting with given that the rewrite will only happen once.

**Comment by bryanwweber** [comment]
This is actually a known thing and in the documentation: http://yaml.readthedocs.io/en/latest/detail.html?highlight=indent#indentation-of-block-sequences

> It is best to always have `indent >= block_seq_indent + 2`
